# Generated by Django 3.1.1 on 2022-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220416_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_item_order', to='core.OrderItem'),
        ),
    ]
